//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zampara {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameObjects {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameObjects() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Zampara.GameObjects", typeof(GameObjects).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200, 1100, 1500, 1800, 2200, 2900, 3100, 3200, 3300, 3800, 4200, 4700.
        /// </summary>
        internal static string Bins {
            get {
                return ResourceManager.GetString("Bins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600, 1200, 1700, 1900, 2500, 2600, 2700, 2800, 3300, 3600, 3650, 3700, 4000, 4500, 4550, 4600.
        /// </summary>
        internal static string BoobyWoman {
            get {
                return ResourceManager.GetString("BoobyWoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1300, 2500, 3500.
        /// </summary>
        internal static string Home1 {
            get {
                return ResourceManager.GetString("Home1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1500, 2800, 4000.
        /// </summary>
        internal static string Home2 {
            get {
                return ResourceManager.GetString("Home2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4500.
        /// </summary>
        internal static string Pants {
            get {
                return ResourceManager.GetString("Pants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3000.
        /// </summary>
        internal static string Shirt {
            get {
                return ResourceManager.GetString("Shirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1500.
        /// </summary>
        internal static string Shoes {
            get {
                return ResourceManager.GetString("Shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150, 250, 400, 700, 1200.
        /// </summary>
        internal static string Trees {
            get {
                return ResourceManager.GetString("Trees", resourceCulture);
            }
        }
    }
}
